### PR TITLE
CurseBreaker added support for Linux and Mac

### PR DESCRIPTION
**Pull request by layday**
See https://github.com/AcidWeb/CurseBreaker/releases/tag/v3.0.1.

### CODE REVIEW

**Comment by layday** [comment]
It looks like it's packaged under Ubuntu but still miraculously works on macOS.

**Comment by torkus** [comment]
this seems fine. I'll merge it tonight when I have a bit of time

**Comment by torkus** [comment]
you know ... if you could figure out a way to package instawow like Cursebreaker I could remove that caveat and solve my hand wringing over the mac preset in the [other PR you opened](https://github.com/ogri-la/wowman-comrades/pull/5).

**Comment by layday** [comment]
Python does not lend itself to that sort of thing. The way the packager, PyInstaller, works is it unpacks the executable into a (new) temporary directory on every invocation.  This is expectedly expensive and - though it might not matter all that much for a {T,G}UI - a 500 ms start-up is going to be noticeable when using a CLI:

```
$ time instawow --version
instawow, version 1.6.1.dev3+g2c31691.d20191022
        0.22 real         0.17 user         0.03 sys
$ time ./dist/instawow-standalone --version
instawow, version 1.6.1.dev3+g2c31691.d20191022
        0.56 real         0.37 user         0.16 sys
```

Imagine now that every `instawow <command>` takes an additional 340 ms to complete. In return I get to roll out my own self-update mechanism, because how are people going to update instawow?  I can appreciate that people might not _want_ to have to separately install the Python language runtime but the net effect is the same - they're gonna get it anyway.  As for the um, cohort, of people who are able to operate instawow but unable to install Python, maybe instawow just isn't for them - they'd probably find themselves much more at home in wowman.   A more reasonable way forward for instawow would be to make it available through e.g. brew, ports, dnf, in a separate repository.

**Comment by layday** [comment]
I sometimes seriously regret writing it in Python.

**Comment by torkus** [comment]
> Imagine now that every instawow <command> takes an additional 340 ms to complete. 

You would get used to it pretty quickly I think. You need not go down the whole TUI route, but you could open a prompt that accepts user input and run the commands that way. Might even be a windows-only thing to get around the latency.

> I sometimes seriously regret writing it in Python.

Ever tried [Grumpy](https://github.com/grumpyhome/grumpy) ? Or [Nim](https://nim-lang.org/)?

**Comment by torkus** [comment]
ah, you corrected a typo as well, cheers.

**Pull request merged**
