### PR TITLE
Add FOSS, source and lang cols to win and mac

### PR DESCRIPTION
**Pull request by layday**

### CODE REVIEW

**Comment by layday** [comment]
History has proven Windows and Mac users do not suffer from cognitive dissonance.

**Comment by torkus** [comment]
I don't want those presets to be condescending or hide important information, but their audience is not 'developers'.

Similar to my opinion on the high bar for an installable application, there is a class of problems/knowledge I don't think the average user of these technologies should have to care about, like the difference between 'source available' and 'f/oss' or whether the application was written in Javascript or Python. 

With the mac preset the 'mac' field is set to the caveated **yes\*** , so we could add the 'language' field back in or change the 'mac' field to **yes**, without caveats. I'm not convinced mac users are any more technically minded than windows users and would err on tightening up the 'mac' field, but it would mean *instawow* disappearing from that preset which I don't want.

I'm fine with making the the `:ui :retail :classic` fields consistently ordered.

**Comment by layday** [comment]
> I don't want those presets to be condescending or hide important information, but their audience is not 'developers'.

I reckon whether a piece of software is FOSS or not is important to many non-developers - the other two fields not so much.

> I'm not convinced mac users are any more technically minded than windows users ...

They probably are, on average. macOS has a fraction of Windows' user base but a little more than half the number of Windows developers (who happen to frequent SO): https://insights.stackoverflow.com/survey/2019#technology-_-developers-primary-operating-systems

As for tightening up the mac field that would leave us with Minion and Twitch, so we'd just be harming our own cause.

**Comment by torkus** [comment]
> I'm not convinced mac users are any more technically minded than windows users ...
> They probably are, on average.

I shouldn't have brought it up ;) I was just really hating the mac experience at the time. Definitely not an OS for me.

> As for tightening up the mac field that would leave us with Minion and Twitch, so we'd just be harming our own cause.

I'm not sure I have a cause. Being privacy minded and transparent are really important but I'm not going to force a horse to drink. If a person doesn't have the curiosity to explore F/OSS, which is so much more prevalent these days than it's ever been, or re-examine their own thoughts on what it is to be a computer user, then I'm not going to beat them over the head about it. But the software will be around for those who do. They may even say 'thank you', which is nice when it happens.

**Comment by layday** [comment]
> I'm not sure I have a cause ...

Well, not a cause, but the purpose, which is to help Mac users find viable alternatives.  Filtering out *instawow* because it involves more steps than downloading a file and running it seems pretty arbitrary to me.  Anyway, I'll close this and you can cherry-pick `0257cc9` if you want.

**Pull request closed without merging**
